from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
V1_METRICS = ROOT / "model_out" / "metrics.json"
V2_METRICS = ROOT / "model_out_v2" / "metrics.json"
OUT_MD = ROOT / "model_out_v2" / "comparison_v1_v2.md"
OUT_JSON = ROOT / "model_out_v2" / "comparison_v1_v2.json"


def fmt_delta(v: float) -> str:
    return f"{v:+.4f}"


def main() -> int:
    if not V1_METRICS.exists():
        print(f"✗ v1 metrics not found: {V1_METRICS}", file=sys.stderr)
        return 1
    if not V2_METRICS.exists():
        print(f"✗ v2 metrics not found: {V2_METRICS}", file=sys.stderr)
        print(f"  Train v2 first: python -m train.v2.train_v2", file=sys.stderr)
        return 1

    v1 = json.loads(V1_METRICS.read_text())
    v2 = json.loads(V2_METRICS.read_text())

    v1_tm = v1["test_metrics"]
    v2_tm = v2["test_metrics"]
    v2_new_features = v2.get("v2_new_features", [])
    v2_new_targets = v2.get("v2_new_targets", [])

    shared = [t for t in v1_tm if t in v2_tm]
    new_only = [t for t in v2_tm if t not in v1_tm]

    deltas = {}
    for t in shared:
        a1, a2 = v1_tm[t]["auc"], v2_tm[t]["auc"]
        deltas[t] = {
            "v1_auc": a1, "v2_auc": a2, "delta_auc": a2 - a1,
            "v1_auprc": v1_tm[t]["auprc"], "v2_auprc": v2_tm[t]["auprc"],
            "delta_auprc": v2_tm[t]["auprc"] - v1_tm[t]["auprc"],
            "v1_brier": v1_tm[t]["brier"], "v2_brier": v2_tm[t]["brier"],
            "delta_brier": v2_tm[t]["brier"] - v1_tm[t]["brier"],
        }
    mean_v1 = sum(d["v1_auc"] for d in deltas.values()) / max(len(deltas), 1)
    mean_v2 = sum(d["v2_auc"] for d in deltas.values()) / max(len(deltas), 1)

    md = []
    md.append("# HEMAX_NEURO v1 vs v2 — production model comparison\n")
    md.append("Auto-generated by `train/v2/compare_v1_v2.py`.\n")
    md.append("## Configuration\n")
    md.append(f"|              | v1                | v2                |")
    md.append(f"|--------------|-------------------|-------------------|")
    md.append(f"| n_features   | {v1['n_features']:<17} | {v2['n_features']:<17} |")
    md.append(f"| n_targets    | {len(v1_tm):<17} | {len(v2_tm):<17} |")
    md.append(f"| n_train      | {v1['n_train']:<17,} | {v2['n_train']:<17,} |")
    md.append(f"| n_test       | {v1['n_test']:<17,} | {v2['n_test']:<17,} |")
    md.append(f"| best_epoch   | {v1['best_epoch']:<17} | {v2['best_epoch']:<17} |")
    md.append("")
    md.append(f"**v2 added features ({len(v2_new_features)}):** `{', '.join(v2_new_features)}`")
    md.append("")
    md.append(f"**v2 added task heads ({len(v2_new_targets)}):** `{', '.join(v2_new_targets)}`")
    md.append("")

    md.append("## Shared targets — direct head-to-head\n")
    md.append("| Target | v1 AUC | v2 AUC | Δ AUC | v1 AUPRC | v2 AUPRC | Δ AUPRC |")
    md.append("|--------|-------:|-------:|------:|---------:|---------:|--------:|")
    for t, d in deltas.items():
        marker = " ▲" if d["delta_auc"] > 0.01 else (" ▼" if d["delta_auc"] < -0.01 else "")
        md.append(
            f"| `{t}` | {d['v1_auc']:.4f} | {d['v2_auc']:.4f} | "
            f"**{fmt_delta(d['delta_auc'])}**{marker} | "
            f"{d['v1_auprc']:.4f} | {d['v2_auprc']:.4f} | "
            f"{fmt_delta(d['delta_auprc'])} |"
        )
    md.append(f"| **MEAN** | **{mean_v1:.4f}** | **{mean_v2:.4f}** | "
              f"**{fmt_delta(mean_v2 - mean_v1)}** | | | |")
    md.append("")

    if new_only:
        md.append("## New task heads (v2 only)\n")
        md.append("| Target | Test AUC | Test AUPRC | Test Brier | n_pos / n |")
        md.append("|--------|---------:|-----------:|-----------:|----------:|")
        for t in new_only:
            m = v2_tm[t]
            md.append(
                f"| `{t}` | {m['auc']:.4f} | {m['auprc']:.4f} | "
                f"{m['brier']:.4f} | {m.get('n_pos', '?')}/{m['n']:,} |"
            )
        md.append("")

    md.append("## Headline\n")
    if mean_v2 - mean_v1 > 0.02:
        md.append(f"- Mean test AUC improved by **{fmt_delta(mean_v2 - mean_v1)}** "
                  f"({mean_v1:.4f} → {mean_v2:.4f}) across {len(deltas)} shared targets.")
    elif mean_v2 - mean_v1 < -0.02:
        md.append(f"- ⚠ Mean test AUC **decreased** by {fmt_delta(mean_v2 - mean_v1)} — "
                  f"investigate before promoting v2.")
    else:
        md.append(f"- Mean test AUC: {mean_v1:.4f} → {mean_v2:.4f} "
                  f"({fmt_delta(mean_v2 - mean_v1)}) — marginal change.")

    top_target = max(deltas, key=lambda t: deltas[t]["delta_auc"])
    md.append(f"- Largest single-target gain: `{top_target}` with "
              f"**{fmt_delta(deltas[top_target]['delta_auc'])} AUC** "
              f"({deltas[top_target]['v1_auc']:.4f} → "
              f"{deltas[top_target]['v2_auc']:.4f}).")
    md.append("")

    md.append("## Reproducibility\n")
    md.append("Both models trained with the same random seed (42), same age × sex "
              "stratification, and the same train/val/test ratio (70/15/15). "
              "Test set membership is comparable because the split is determined "
              "by SEQN order under the same seed, and v2 is a strict superset of "
              "v1 in terms of features.")
    md.append("")

    OUT_MD.write_text("\n".join(md))
    OUT_JSON.write_text(json.dumps({
        "v1": v1_tm, "v2": v2_tm,
        "shared_targets": shared, "new_only_targets": new_only,
        "deltas": deltas,
        "mean_v1_auc_shared": mean_v1,
        "mean_v2_auc_shared": mean_v2,
        "v2_new_features": v2_new_features,
        "v2_new_targets": v2_new_targets,
    }, indent=2))

    print("\n".join(md))
    print(f"\n✓ Saved {OUT_MD}")
    print(f"✓ Saved {OUT_JSON}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
